name: Build Kivy APK

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build APK with Docker and Buildozer
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            kivy/buildozer \
            bash -c "sudo chown -R $(id -u):$(id -g) /app && cd /app && buildozer -v android debug"
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk