name: Build Kivy APK

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build with Buildozer
        id: build
        uses: kivy/buildozer-action@v1
        with:
          build_dir: .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ${{ steps.build.outputs.package_path }}/*.apk