name: Build Kivy APK

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build APK with Docker and Buildozer (Simplified)
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            kivy/buildozer \
            android debug
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          # Usamos um wildcard (**) para encontrar a pasta bin, não importa a profundidade
          path: "**/bin/*.apk"